micronaut:
  application:
    name: helloParisJugAtAgorapulse
netty:
  default:
    allocator:
      max-order: 3
console:
  enabled: true
  addresses:
    - /127.0.0.1
    - /0:0:0:0:0:0:0:1
  header-name: X-Console-Verify
  header-value: 2ee515c4-2136-411e-9b85-e4cccfc18762